version: '3.1'
services:
    rabbitmq:
        image: rabbitmq:3.8.19-management
        container_name: rabbitmq
        restart: on-failure
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - back
        environment:
            - "RABBITMQ_DEFAULT_USER=guest"
            - "RABBITMQ_DEFAULT_PASS=guest"

    sql_server:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: sql_server
        ports:
            - 1433:1433
        networks:
            - back
        environment:
            SA_PASSWORD: MySecretPassword!
            ACCEPT_EULA: "Y"

networks:
    back:
        driver: bridge