// eslint-disable-next-line no-shadow
export enum TimeZone {
    // https://docs.microsoft.com/ru-ru/dotnet/api/officedevpnp.core.enums.timezone?view=sharepoint-pnpcoreol-3.2.1810
    UTC_CASABLANCA = 'UTC_CASABLANCA',
    UTC_COORDINATED_UNIVERSAL_TIME = 'UTC_COORDINATED_UNIVERSAL_TIME',
    UTC_GREENWICH_MEAN_TIME_DUBLIN_EDINBURGH_LISBON_LONDON = 'UTC_GREENWICH_MEAN_TIME_DUBLIN_EDINBURGH_LISBON_LONDON',
    UTC_MONROVIA = 'UTC_MONROVIA',
    UTCMINUS0100_AZORES = 'UTCMINUS0100_AZORES',
    UTCPLUS0200_HELSINKI_KYIV_RIGA_SOFIA_TALLINN_VILNIUS = 'UTCPLUS0200_HELSINKI_KYIV_RIGA_SOFIA_TALLINN_VILNIUS',
}
